const logger = require("./logger");

/**
 * Formats an array of AI reviews into a GitHub PR comment with collapsible details.
 * Only includes files with severity > 'none' (i.e., files that need attention).
 *
 * @param {Array<object>} reviews - Array of review objects with structure:
 *   { filename, severity, summary, suggestions[], securityFlags[], approved }
 *
 * @returns {string} - Formatted markdown comment body, or empty string if no issues
 */
function formatReviewsAsMarkdown(reviews) {
    try {
        if (!Array.isArray(reviews) || reviews.length === 0) {
            logger.warn("No reviews provided to formatter");
            return "";
        }

        // Filter for issues: severity > 'none'
        const severityOrder = { none: 0, low: 1, medium: 2, high: 3 };
        const issuesOnly = reviews.filter(
            (review) => severityOrder[review.severity] > 0
        );

        if (issuesOnly.length === 0) {
            logger.info("No issues found in reviews; returning empty comment");
            return "";
        }

        // Build the comment header
        let commentBody = `## 🤖 AI Code Review\n\n`;
        commentBody += `Found **${issuesOnly.length}** file(s) with issues:\n\n`;

        // Add each file as a collapsible section
        issuesOnly.forEach((review) => {
            const severityEmoji = getSeverityEmoji(review.severity);
            const isApproved = review.approved ? "✅ Approved" : "❌ Rejected";

            commentBody += `<details>\n`;
            commentBody += `<summary><strong>${severityEmoji} ${review.filename}</strong> — ${review.severity.toUpperCase()} (${isApproved})</summary>\n\n`;

            // Summary
            commentBody += `**Summary:** ${review.summary}\n\n`;

            // Suggestions
            if (review.suggestions && review.suggestions.length > 0) {
                commentBody += `**Suggestions:**\n`;
                review.suggestions.forEach((suggestion) => {
                    commentBody += `- ${suggestion}\n`;
                });
                commentBody += `\n`;
            }

            // Security flags
            if (review.securityFlags && review.securityFlags.length > 0) {
                commentBody += `**🔒 Security Flags:**\n`;
                review.securityFlags.forEach((flag) => {
                    commentBody += `- ⚠️ ${flag}\n`;
                });
                commentBody += `\n`;
            }

            commentBody += `</details>\n\n`;
        });

        // Footer
        commentBody += `---\n`;
        commentBody += `*This review was generated by an AI code reviewer.*\n`;

        return commentBody;
    } catch (error) {
        logger.error("Error formatting reviews as markdown", {
            error: error.message,
        });
        return "";
    }
}

/**
 * Maps severity level to an emoji for visual distinction.
 * @param {string} severity - 'low', 'medium', 'high', 'none'
 * @returns {string} - Emoji
 */
function getSeverityEmoji(severity) {
    const emojiMap = {
        high: "🔴",
        medium: "🟡",
        low: "🟢",
        none: "⚪",
    };
    return emojiMap[severity] || "❓";
}

module.exports = {
    formatReviewsAsMarkdown,
    getSeverityEmoji,
};
