const logger = require("./logger");

function getSeverityEmoji(severity) {
    const emojiBySeverity = {
        critical: "🟣",
        high: "🔴",
        medium: "🟡",
        low: "🟢",
        none: "⚪",
    };

    return emojiBySeverity[severity] || "❓";
}

/**
 * Formats an array of AI reviews into a GitHub PR comment with collapsible details.
 * Only includes files with severity > 'none' (i.e., files that need attention).
 *
 * @param {Array<object>} reviews - Array of review objects with structure:
 *   { filename, severity, summary, suggestions[], securityFlags[], approved }
 *
 * @returns {string} - Formatted markdown comment body, or empty string if no issues
 */
function formatReviewsAsMarkdown(reviews) {
    try {
        if (!Array.isArray(reviews) || reviews.length === 0) {
            logger.warn("No reviews provided to formatter");
            return "";
        }

        // Filter for issues: severity > 'none'
        const severityOrder = { none: 0, low: 1, medium: 2, high: 3, critical: 4 };
        const issuesOnly = reviews.filter(
            (review) => severityOrder[review.severity] > 0
        );

        if (issuesOnly.length === 0) {
            logger.info("No issues found in reviews; returning empty comment");
            return "";
        }

        // Build the comment header
        let commentBody = `## 🤖 AI Code Review\n\n`;
        commentBody += `Found **${issuesOnly.length}** file(s) with issues:\n\n`;

        // Group issues into a section per severity level, ordered low to high
        const severityLabels = {
            low: "🟢 Low Severity",
            medium: "🟡 Medium Severity",
            high: "🔴 High Severity",
            critical: "🟣 Critical Severity",
        };

        Object.keys(severityLabels).forEach((severity) => {
            const group = issuesOnly.filter((review) => review.severity === severity);
            if (group.length === 0) return;

            commentBody += `### ${severityLabels[severity]} (${group.length})\n\n`;

            // Add each file as a collapsible section
            group.forEach((review) => {
                const reviewStatus = review.approved ? "✅ Approved" : "❌ Rejected";
                const severityEmoji = getSeverityEmoji(review.severity);

                commentBody += `<details>\n`;
                commentBody += `<summary><strong>${review.filename}</strong> — ${severityEmoji} ${review.severity.toUpperCase()} (${reviewStatus})</summary>\n\n`;

                // Summary
                commentBody += `**Summary:** ${review.summary}\n\n`;

                if (review.keyPrinciple) {
                    commentBody += `**Key Principle:** \`${review.keyPrinciple}\`\n\n`;
                }

                if (review.didWell) {
                    commentBody += `**✅ Done Well:** ${review.didWell}\n\n`;
                }

                // Patch snippet
                if (review.patch) {
                    commentBody += `**Relevant Code:**\n`;
                    commentBody += `\`\`\`\n${review.patch}\n\`\`\`\n\n`;
                }

                // Suggestions
                if (review.suggestions && review.suggestions.length > 0) {
                    commentBody += `**Suggestions:**\n`;
                    review.suggestions.forEach((suggestion) => {
                        // Guard: support both old flat strings and new structured objects
                        if (typeof suggestion === "string") {
                            commentBody += `- ${suggestion}\n`;
                            return;
                        }

                        const badge = suggestion.level === "junior"
                            ? "🟢 Junior"
                            : suggestion.level === "senior"
                                ? "🔵 Senior"
                                : "🟡 All";

                        commentBody += `- **[${badge}]** ${suggestion.issue}\n`;
                        commentBody += `  - **Why:** ${suggestion.why}\n`;
                        commentBody += `  - **Fix:** \`${suggestion.fix}\`\n`;
                    });
                    commentBody += `\n`;
                }

                if (review.securityFlags && review.securityFlags.length > 0) {
                    commentBody += `**🔒 Security Flags:**\n`;
                    review.securityFlags.forEach((flag) => {
                        commentBody += `- ${flag}\n`;
                    });
                    commentBody += `\n`;
                }

                commentBody += `</details>\n\n`;
            });
        });

        // Footer
        commentBody += `---\n`;
        commentBody += `*This review was generated by an AI code reviewer.*\n`;

        return commentBody;
    } catch (error) {
        logger.error("Error formatting reviews as markdown", {
            error: error.message,
        });
        return "";
    }
}

module.exports = {
    formatReviewsAsMarkdown,
    getSeverityEmoji,
};
